name: store
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.3.2
  smooth_page_indicator: ^1.1.0
  get:
  carousel_slider: ^4.2.1
  get_storage: ^2.1.1
  # fire base
  firebase_core: ^2.31.1
  firebase_auth: ^4.14.0
  cloud_firestore: ^4.13.1
  lottie: ^2.7.0
  image_picker: ^1.0.4
  connectivity_plus: ^5.0.2
  firebase_storage: ^11.7.7
  shimmer: ^3.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets: 
    - assets/images/splash_image/
    - assets/images/onboarding_image/
    - assets/icons/
    - assets/fonts/
    - assets/logos/
    - assets/images/
    - assets/icons/categories/
    - assets/images/banner/
    - assets/images/brands/
    - assets/images/animations/
    - assets/images/products/