import 'package:store/features/shop/models/banner_model.dart';
import 'package:store/features/shop/models/brand_model.dart';
import 'package:store/features/shop/models/category_model.dart';
import 'package:store/features/shop/models/product_model.dart';
import 'package:store/utils/constants/image_string.dart';

class DummyData {
  static final List<ProductModel> product = [
    ProductModel(
      id: '1',
      stock: 10,
      price: 100.0,
      title: 'Acer Laptop',
      salePercentage: 10.0,
      isFeatured: true,
      brand: 'Acer',
      description: '',
      categoryId: '2',
      image: ImageString.acerProduct1,
      productType: '',
    ),
    ProductModel(
      id: '2',
      stock: 10,
      price: 100.0,
      title: 'Acer Laptop',
      salePercentage: 10.0,
      isFeatured: true,
      brand: 'Acer',
      description: '',
      categoryId: '2',
      image: ImageString.acerProduct2,
      productType: '',
    ),
    ProductModel(
      id: '3',
      stock: 10,
      price: 100.0,
      title: 'Acer Laptop',
      salePercentage: 10.0,
      isFeatured: true,
      brand: 'Acer',
      description: '',
      categoryId: '2',
      image: ImageString.acerProduct3,
      productType: '',
    ),
    ProductModel(
      id: '4',
      stock: 10,
      price: 100.0,
      title: 'Acer Laptop',
      salePercentage: 10.0,
      isFeatured: true,
      brand: 'Acer',
      description: '',
      categoryId: '2',
      image: ImageString.acerProduct4,
      productType: '',
    ),
    ProductModel(
      id: '5',
      stock: 10,
      price: 100.0,
      title: 'Acer Laptop',
      salePercentage: 10.0,
      isFeatured: true,
      brand: 'Acer',
      description: '',
      categoryId: '2',
      image: ImageString.acerProduct5,
      productType: '',
    ),
    ProductModel(
      id: '6',
      stock: 10,
      price: 100.0,
      title: 'Adidas',
      salePercentage: 10.0,
      isFeatured: true,
      brand: 'Adidas',
      description: '',
      categoryId: '3',
      image: ImageString.adidasProduct1,
      productType: '',
    ),
    ProductModel(
      id: '7',
      stock: 10,
      price: 100.0,
      title: 'Adidas',
      salePercentage: 10.0,
      isFeatured: true,
      brand: 'Adidas',
      description: '',
      categoryId: '3',
      image: ImageString.adidasProduct2,
      productType: '',
    ),
    ProductModel(
      id: '8',
      stock: 10,
      price: 100.0,
      title: 'Iphone',
      salePercentage: 10.0,
      isFeatured: true,
      brand: 'Apple',
      description: '',
      categoryId: '2',
      image: ImageString.appleProduct1,
      productType: '',
    ),
    ProductModel(
      id: '9',
      stock: 10,
      price: 100.0,
      title: 'Iphone',
      salePercentage: 10.0,
      isFeatured: true,
      brand: 'Apple',
      description: '',
      categoryId: '2',
      image: ImageString.appleProduct2,
      productType: '',
    ),
    ProductModel(
      id: '10',
      stock: 10,
      price: 100.0,
      title: 'Iphone',
      salePercentage: 10.0,
      isFeatured: true,
      brand: 'Apple',
      description: '',
      categoryId: '2',
      image: ImageString.appleProduct3,
      productType: '',
    ),
    ProductModel(
      id: '11',
      stock: 10,
      price: 100.0,
      title: 'Iphone',
      salePercentage: 10.0,
      isFeatured: true,
      brand: 'Apple',
      description: '',
      categoryId: '2',
      image: ImageString.appleProduct4,
      productType: '',
    ),
    ProductModel(
      id: '12',
      stock: 10,
      price: 100.0,
      title: 'Iphone',
      salePercentage: 10.0,
      isFeatured: true,
      brand: 'Apple',
      description: '',
      categoryId: '2',
      image: ImageString.appleProduct5,
      productType: '',
    ),
    ProductModel(
      id: '13',
      stock: 10,
      price: 100.0,
      title: 'Iphone',
      salePercentage: 10.0,
      isFeatured: true,
      brand: 'Apple',
      description: '',
      categoryId: '2',
      image: ImageString.appleProduct6,
      productType: '',
    ),
    ProductModel(
      id: '14',
      stock: 10,
      price: 100.0,
      title: 'Ikea product',
      salePercentage: 10.0,
      isFeatured: true,
      brand: 'Ikea',
      description: '',
      categoryId: '5',
      image: ImageString.ikeaProduct1,
      productType: '',
    ),
    ProductModel(
      id: '15',
      stock: 10,
      price: 100.0,
      title: 'Ikea product',
      salePercentage: 10.0,
      isFeatured: true,
      brand: 'Ikea',
      description: '',
      categoryId: '5',
      image: ImageString.ikeaProduct2,
      productType: '',
    ),
    ProductModel(
      id: '16',
      stock: 10,
      price: 100.0,
      title: 'Ikea product',
      salePercentage: 10.0,
      isFeatured: true,
      brand: 'Ikea',
      description: '',
      categoryId: '5',
      image: ImageString.ikeaProduct3,
      productType: '',
    ),
    ProductModel(
      id: '17',
      stock: 10,
      price: 100.0,
      title: 'Ikea product',
      salePercentage: 10.0,
      isFeatured: true,
      brand: 'Ikea',
      description: '',
      categoryId: '5',
      image: ImageString.ikeaProduct4,
      productType: '',
    ),
    ProductModel(
      id: '18',
      stock: 10,
      price: 100.0,
      title: 'Ikea product',
      salePercentage: 10.0,
      isFeatured: true,
      brand: 'Ikea',
      description: '',
      categoryId: '5',
      image: ImageString.ikeaProduct5,
      productType: '',
    ),
    ProductModel(
      id: '19',
      stock: 10,
      price: 100.0,
      title: 'Ikea product',
      salePercentage: 10.0,
      isFeatured: true,
      brand: 'Ikea',
      description: '',
      categoryId: '5',
      image: ImageString.ikeaProduct6,
      productType: '',
    ),
    ProductModel(
      id: '20',
      stock: 10,
      price: 100.0,
      title: 'Zara product',
      salePercentage: 10.0,
      isFeatured: true,
      brand: 'Zara',
      description: '',
      categoryId: '3',
      image: ImageString.zaraProduct1,
      productType: '',
    ),
    ProductModel(
      id: '21',
      stock: 10,
      price: 100.0,
      title: 'Zara product',
      salePercentage: 10.0,
      isFeatured: true,
      brand: 'Zara',
      description: '',
      categoryId: '3',
      image: ImageString.zaraProduct2,
      productType: '',
    ),
    ProductModel(
      id: '22',
      stock: 10,
      price: 100.0,
      title: 'Zara product',
      salePercentage: 10.0,
      isFeatured: true,
      brand: 'Zara',
      description: '',
      categoryId: '3',
      image: ImageString.zaraProduct3,
      productType: '',
    ),
    ProductModel(
      id: '23',
      stock: 10,
      price: 100.0,
      title: 'Zara product',
      salePercentage: 10.0,
      isFeatured: true,
      brand: 'Zara',
      description: '',
      categoryId: '3',
      image: ImageString.zaraProduct4,
      productType: '',
    ),
    ProductModel(
      id: '24',
      stock: 10,
      price: 100.0,
      title: 'Zara product',
      salePercentage: 10.0,
      isFeatured: true,
      brand: 'Zara',
      description: '',
      categoryId: '3',
      image: ImageString.zaraProduct5,
      productType: '',
    ),
    ProductModel(
      id: '25',
      stock: 10,
      price: 100.0,
      title: 'Zara product',
      salePercentage: 10.0,
      isFeatured: true,
      brand: 'Zara',
      description: '',
      categoryId: '3',
      image: ImageString.zaraProduct6,
      productType: '',
    ),
  ];

  static final List<BannerModel> banners = [
    BannerModel(
      id: '1',
      image: ImageString.bannerImage1,
    ),
    BannerModel(
      id: '2',
      image: ImageString.bannerImage2,
    ),
    BannerModel(
      id: '3',
      image: ImageString.bannerImage3,
    ),
    BannerModel(
      id: '4',
      image: ImageString.bannerImage4,
    ),
    BannerModel(
      id: '5',
      image: ImageString.bannerImage5,
    ),
    BannerModel(
      id: '6',
      image: ImageString.bannerImage6,
    ),
    BannerModel(
      id: '7',
      image: ImageString.bannerImage7,
    ),
    BannerModel(
      id: '8',
      image: ImageString.bannerImage8,
    ),
  ];

  static final List<CategoryModel> categories = [
    CategoryModel(
        id: '1',
        image: ImageString.sportIcon,
        name: 'Sports',
        isFeatured: true),
    CategoryModel(
        id: '5',
        image: ImageString.furnitureIcon,
        name: 'Furniture',
        isFeatured: true),
    CategoryModel(
        id: '2',
        image: ImageString.electronicsIcon,
        name: 'Electronics',
        isFeatured: true),
    CategoryModel(
        id: '3',
        image: ImageString.clothIcon,
        name: 'Clothes',
        isFeatured: true),
    CategoryModel(
        id: '4',
        image: ImageString.animalIcon,
        name: 'Animals',
        isFeatured: true),
    CategoryModel(
        id: '6', image: ImageString.shoeIcon, name: 'Shoes', isFeatured: true),
    CategoryModel(
        id: '7',
        image: ImageString.cosmeticsIcon,
        name: 'Cosmetics',
        isFeatured: true),
    CategoryModel(
        id: '14',
        image: ImageString.jeweleryIcon,
        name: 'Jewelry',
        isFeatured: true),
  ];
  static final List<BrandModel> brands = [
    BrandModel(
      id: '1',
      name: 'Acer',
      image: ImageString.acer,
      isFeatured: false,
    ),
    BrandModel(
      id: '2',
      name: 'Adidas',
      image: ImageString.adidas,
      isFeatured: false,
    ),
    BrandModel(
      id: '3',
      name: 'Apple',
      image: ImageString.apple,
      isFeatured: true,
    ),
    BrandModel(
      id: '4',
      name: 'Ikea',
      image: ImageString.ikea,
      isFeatured: true,
    ),
    BrandModel(
      id: '5',
      name: 'Zara',
      image: ImageString.zara,
      isFeatured: true,
    ),
    BrandModel(
      id: '6',
      name: 'Jordan',
      image: ImageString.jordan,
      isFeatured: false,
    ),
    BrandModel(
      id: '7',
      name: 'Kenwood',
      image: ImageString.kenwood,
      isFeatured: false,
    ),
    BrandModel(
      id: '8',
      name: 'Nike',
      image: ImageString.nike,
      isFeatured: true,
    ),
    BrandModel(
      id: '9',
      name: 'Puma',
      image: ImageString.puma,
      isFeatured: false,
    ),
    BrandModel(
      id: '10',
      name: 'Herman Miller',
      image: ImageString.herman,
      isFeatured: false,
    ),
  ];
}
